### PR TITLE
Generator Plugin

### PR DESCRIPTION
**Pull request by anthonydevelops**
WIP of the grpc implmentation, along with a Dockerfile that is aimed to be running (and testing) our backend. Right now, I am going to be working on getting the connection between ETCD & gRPC working correctly by building the functionality of the simple proto handlers. Let me know if there is anything I should be doing differently, any errors, or just general advice.

Current Goal: Get the docker container running with a connection to ETCD by the end of Friday.

### CODE REVIEW

**Comment by anthonydevelops** [comment]
Currently, I'm confused with certain issues using grpc/etcd plugins with my grpcserver plugin. I created custom flags such as **-db-config** or my plugin flag **-grpcserver-config**, but they don't seem to register either on their own or with the grpc/etcd plugin flags. This led me to use only the flags set as **-grpc-config** and **-etcd-config**, since I'm calling their plugin, which work and my agent *seems* to be working. So my question is, is this supposed to be working this way? I've been initializing the default flags of the plugins in my `RegisterFlags()` function, so is this the right way or am I doing something wrong? When I do `go run cmd/agent/main.go` by itself without flags, the .conf files can't be found even if they're in the same directory as `/agent` or `/plugins/grpcserver`, so I must specify them.

Errors w/ custom:
flag-errors

Working w/ declared default flags & connects to etcd:
conn-2-23-19

How I initialized my dependencies in **plugin_impl_grpc.go**: 
```golang
type Deps struct {  
    infra.PluginDeps
    GRPC grpc.Server
    ETCD *etcd.DefaultPlugin
}
```

How I initialized my dependencies in **options.go**:
```golang
...
p.GRPC = grpc.NewPlugin( 
    grpc.UseHTTP(&rest.DefaultPlugin), 
)
p.ETCD = &etcd.DefaultPlugin
...
```

After building the docker image, I ran my code in interactive to do manual testing on a linux container since I have a windows computer: `docker run -it --name server --privileged --rm dev/osseus bash`.

**Comment by anthonydevelops** [comment]
Figured out my error with the flags, working on it now, will update this coming morning.

**Comment by anthonydevelops** [comment]
@brecode I'm having an issue testing my server with an example client. The client cannot connect to the server, even though the client is correctly dialing the server's port (:9111) using WithInsecure(); this is without including the connection to ETCD as well (since that uses docker), just a simple message in my handlers that would be returning a string when sent a request. 

**error**: `transport: Error while dialing dial tcp 127.0.0.1:9111: connect: connection refused`

```golang
// Client connection using address: localhost:9111 (same as server endpoint)
conn, err := grpc.Dial(address, grpc.WithInsecure())
if err != nil {
	logrus.DefaultLogger().Fatalf("did not connect: %v", err)
	}
defer conn.Close()
c := pb.NewGrpcClient(conn)

r, err := c.GetPlugin(context.Background(), &pb.GetPluginRequest{Id: "test"})
```

I'm using Windows Subsystem for Linux, which might be the issue in itself, since I can't run the agent on a Windows computer. Instead of dual-booting I chose this option, but two instances of the bash shell might not be able to recognize eachother so I'm not sure I should hassle my way through that.

This led me to try to run two instances of the same container on docker, where I run one using the client and the other using the server, but then the containers are not configured to talk to eachother on the same network. Would this be a good time to get our containers connected in a network using docker-compose? 

I read up on it and it seems pretty cool, allowing us to create separate networks such as: 

**frontend** - react
**backend** - restapi & grpcserver
**kv** - etcd 

This would also allow me to easily test two instances of the same container if I set them up in the same network, such as testing my server with a client for now, since they'll both be sharing the same connection, along with testing it using ETCD?

---

Also, the flag stuff that I tried didn't work after all, the next step would be to use flagSet but i don't know if overriding the flags of grpc/etcd is the direction I should be going since there does seem to be a connection happening already.

**Comment by anthonydevelops** [comment]
Last night I installed Linux on another laptop and tested things. Using a client, I get results back from the server, but I realize now that my dB connection is wrong most likely after seeing other examples (I wasn’t calling a broker and I’m not passing the plugin itself to the handlers). With passing just strings back, things seem to be working, so I’m working again on the dB connection. There was a tutorial posted under /examples in Ligato/cn-infra, so I’m looking into that.

Also, there is an error in the **build-agent.sh**, where under “dep ensure -vendor-only” there should be a line just calling “dep ensure” since the model isn’t added using -vendor-only.

**Comment by brecode** [comment]
Looks ok. Merging for now but please let me know what you want to do with the consumer you start

**Pull request merged**
